# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
name: Entry CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - release
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'


concurrency:
  group: ${{github.workflow}}-${{ github.ref }}-${{vars.DIST_CHANNEL}}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write



jobs:
  prepare:
    name: Prepare shared data for multi-platform compilation
    runs-on: ubuntu-latest
    outputs:
      APP_VERSION: ${{ steps.APP_VERSION.outputs.APP_VERSION }}
      COMMIT_TIMESTAMP: ${{ steps.COMMIT_TIMESTAMP.outputs.COMMIT_TIMESTAMP }}
      APP_FULL_VERSION: ${{ steps.APP_FULL_VERSION.outputs.APP_FULL_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - id: COMMIT_TIMESTAMP
        run: echo "COMMIT_TIMESTAMP=$(git show -s --format=%ct ${{ github.sha }})" >> $GITHUB_OUTPUT
      - id: APP_VERSION
        run: echo "APP_VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - id: APP_FULL_VERSION
        run: echo "APP_FULL_VERSION=${{ steps.APP_VERSION.outputs.APP_VERSION }}-${{vars.DIST_CHANNEL}}.${{ steps.COMMIT_TIMESTAMP.outputs.COMMIT_TIMESTAMP }}" >> $GITHUB_OUTPUT
      - run: |
          echo "- \`COMMIT_TIMESTAMP\`: ${{ steps.COMMIT_TIMESTAMP.outputs.COMMIT_TIMESTAMP }}" >> $GITHUB_STEP_SUMMARY
          echo "- \`APP_VERSION\`: ${{ steps.APP_VERSION.outputs.APP_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- \`APP_FULL_VERSION\`: ${{ steps.APP_FULL_VERSION.outputs.APP_FULL_VERSION }}" >> $GITHUB_STEP_SUMMARY

  compile-and-test:
    needs:
      - prepare
    permissions:
      contents: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/compile-and-test.yml
    with:
      renderer-template: vanilla-ts
      app-version: ${{ needs.prepare.outputs.APP_FULL_VERSION }}
      distribution-channel: ${{vars.DIST_CHANNEL}}

  deploy:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    needs:
      - prepare
      - compile-and-test
    uses: ./.github/workflows/deploy.yml
    with:
      distribution-channel: ${{ vars.DIST_CHANNEL }}
      app-version: ${{ needs.prepare.outputs.APP_FULL_VERSION }}
